# Generated by Django 4.2.28 on 2026-02-11 05:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_customuser_id_alter_facultyprofile_id_and_more'),
        ('academics', '0002_alter_course_id_alter_department_id_alter_subject_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(auto_now_add=True, help_text='Date when the student enrolled')),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('WITHDRAWN', 'Withdrawn')], default='ENROLLED', help_text='Current enrollment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course the student is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.course')),
                ('student', models.ForeignKey(help_text='Student enrolled in the course', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-date_enrolled'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_grades', models.JSONField(default=dict, help_text='JSON data containing previous grades and academic records')),
                ('year_completed', models.IntegerField(help_text='Academic year completed (e.g., 2025)', validators=[django.core.validators.MinValueValidator(1900)])),
                ('semester', models.IntegerField(blank=True, help_text='Semester number (optional)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text='GPA for this academic period', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student whose academic history is recorded', on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Academic History',
                'verbose_name_plural': 'Academic Histories',
                'ordering': ['-year_completed', '-semester'],
                'unique_together': {('student', 'year_completed', 'semester')},
            },
        ),
    ]
