# Generated by Django 4.2.28 on 2026-02-11 04:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_course_id_alter_department_id_alter_subject_id_and_more'),
        ('users', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(help_text='Unique student enrollment number', max_length=20, unique=True)),
                ('current_semester', models.IntegerField(default=1, help_text='Current semester number', validators=[django.core.validators.MinValueValidator(1)])),
                ('batch_year', models.IntegerField(help_text='Year of admission/batch (e.g., 2026)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Student department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.department')),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['-batch_year', 'enrollment_number'],
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee identification number', max_length=20, unique=True)),
                ('designation', models.CharField(help_text='Faculty designation (e.g., Professor, Lecturer, Assistant Professor)', max_length=100)),
                ('specialization', models.CharField(blank=True, help_text='Area of specialization', max_length=200, null=True)),
                ('date_of_joining', models.DateField(blank=True, help_text='Date of joining the institution', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Faculty department', on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='academics.department')),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Profile',
                'verbose_name_plural': 'Faculty Profiles',
                'ordering': ['department', 'designation'],
            },
        ),
    ]
