# Generated by Django 4.2.28 on 2026-02-12 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_id_alter_facultyprofile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Username at time of action (preserved even if user deleted)', max_length=150)),
                ('action', models.CharField(choices=[('POST', 'Create'), ('PUT', 'Update'), ('PATCH', 'Partial Update'), ('DELETE', 'Delete')], help_text='HTTP method used', max_length=10)),
                ('endpoint', models.CharField(help_text='API endpoint/URL path accessed', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string')),
                ('request_body', models.TextField(blank=True, help_text='Request body/payload (sanitized)')),
                ('response_status', models.IntegerField(blank=True, help_text='HTTP response status code', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action was performed')),
                ('execution_time', models.FloatField(blank=True, help_text='Request execution time in seconds', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='users_audit_timesta_f4ba63_idx'), models.Index(fields=['user', '-timestamp'], name='users_audit_user_id_29b33e_idx'), models.Index(fields=['action', '-timestamp'], name='users_audit_action_e79129_idx'), models.Index(fields=['endpoint', '-timestamp'], name='users_audit_endpoin_04a5db_idx')],
            },
        ),
    ]
