# Generated by Django 4.2.28 on 2026-02-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_alter_course_id_alter_department_id_alter_subject_id_and_more'),
        ('users', '0004_alter_customuser_id_alter_facultyprofile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the class')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], help_text='Attendance status', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, help_text='Faculty member who marked the attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to='users.facultyprofile')),
                ('student', models.ForeignKey(help_text='Student whose attendance is being recorded', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.studentprofile')),
                ('subject', models.ForeignKey(help_text='Subject for which attendance is recorded', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'student__enrollment_number'],
                'indexes': [models.Index(fields=['date', 'subject'], name='attendance__date_7e905a_idx'), models.Index(fields=['student', 'date'], name='attendance__student_76a8d7_idx')],
                'unique_together': {('student', 'subject', 'date')},
            },
        ),
    ]
