# Generated by Django 6.0.2 on 2026-04-17 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_subject_faculty'),
        ('attendance', '0002_alter_attendance_options_and_more'),
        ('users', '0007_alter_studentprofile_options_studentprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_string', models.CharField(help_text="Batch identifier (e.g., '2024-IMG', '2023-CSE')", max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed_by_admin', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin review notes')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_report_submissions', to='users.facultyprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_reports', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_report_submissions', to='academics.subject')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['faculty', 'subject'], name='attendance__faculty_8014cc_idx'), models.Index(fields=['batch_string'], name='attendance__batch_s_6e2831_idx'), models.Index(fields=['is_reviewed_by_admin'], name='attendance__is_revi_ff1f0d_idx')],
            },
        ),
    ]
