# Generated by Django 6.0.2 on 2026-04-21 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_timetablepdf'),
        ('attendance', '0003_attendancereportsubmission'),
        ('users', '0007_alter_studentprofile_options_studentprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereportsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the submission', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendancereportsubmission',
            index=models.Index(fields=['status'], name='attendance__status_ecb110_idx'),
        ),
    ]
