# Generated by Django 4.2.28 on 2026-02-12 20:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_alter_course_id_alter_department_id_alter_subject_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title/name of the resource', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the resource content', null=True)),
                ('file', models.FileField(help_text='File upload (PDF, DOC, PPT, images, videos, etc.)', upload_to='resources/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'txt', 'zip', 'rar', 'jpg', 'jpeg', 'png', 'mp4', 'avi'])])),
                ('resource_type', models.CharField(choices=[('NOTES', 'Lecture Notes'), ('ASSIGNMENT', 'Assignment'), ('REFERENCE', 'Reference Material'), ('SLIDES', 'Presentation Slides'), ('VIDEO', 'Video Link'), ('OTHER', 'Other')], default='NOTES', help_text='Type of resource', max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('download_count', models.IntegerField(default=0, help_text='Number of times this resource has been downloaded')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this resource is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(help_text='Subject this resource belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academics.subject')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this resource (typically faculty)', on_delete=django.db.models.deletion.CASCADE, related_name='resources_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Resource',
                'verbose_name_plural': 'Learning Resources',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject', '-created_at'], name='communicati_subject_c5c010_idx'), models.Index(fields=['uploaded_by', '-created_at'], name='communicati_uploade_968f09_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the notice', max_length=200)),
                ('content', models.TextField(help_text='Main content/body of the notice')),
                ('audience', models.CharField(choices=[('ALL', 'All Users'), ('STUDENTS', 'Students Only'), ('FACULTY', 'Faculty Only')], default='ALL', help_text='Target audience for this notice', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this notice is currently active/visible')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', help_text='Priority level of the notice', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date/time for the notice', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this notice (typically admin or faculty)', on_delete=django.db.models.deletion.CASCADE, related_name='notices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='communicati_created_8b201c_idx'), models.Index(fields=['audience', 'is_active'], name='communicati_audienc_e8225d_idx')],
            },
        ),
    ]
