# Generated by Django 6.0.2 on 2026-03-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='resource_affected',
            field=models.CharField(blank=True, help_text='Resource/model affected by this action (e.g., Grade, Attendance)', max_length=255),
        ),
    ]
