# Generated by Django 6.0.2 on 2026-03-25 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_customregistrationfield_program'),
        ('users', '0006_auditlog_resource_affected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-batch_year', 'reg_no'], 'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Residential address', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object storing custom registration field values (e.g., {"aadhar": "1234-5678-9012", "samagra_id": "ABC123"})'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], help_text='Gender', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Academic program the student is enrolled in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.program'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='reg_no',
            field=models.CharField(blank=True, help_text='Unique student registration number', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_number',
            field=models.CharField(help_text='Unique student enrollment number (alias for reg_no)', max_length=20, unique=True),
        ),
    ]
