# Generated by Django 6.0.2 on 2026-04-23 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_studentprofile_options_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PAPER', 'Research Paper'), ('PROJECT', 'Project'), ('OTHER', 'Other')], default='PAPER', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='faculty_works/%Y/%m/')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='users.facultyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['faculty', 'is_public'], name='users_facul_faculty_121945_idx')],
            },
        ),
    ]
