# Generated by Django 4.2.28 on 2026-02-12 20:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_alter_course_id_alter_department_id_alter_subject_id_and_more'),
        ('users', '0004_alter_customuser_id_alter_facultyprofile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the assessment (e.g., Midterm Exam, Quiz 1)', max_length=200)),
                ('assessment_type', models.CharField(choices=[('EXAM', 'Examination'), ('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment'), ('PROJECT', 'Project'), ('LAB', 'Lab Work'), ('PRESENTATION', 'Presentation'), ('OTHER', 'Other')], default='EXAM', help_text='Type of assessment', max_length=20)),
                ('max_marks', models.DecimalField(decimal_places=2, help_text='Maximum marks for this assessment', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('weightage', models.DecimalField(decimal_places=2, help_text='Weightage percentage in final grade (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_conducted', models.DateField(blank=True, help_text='Date when assessment was conducted', null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about the assessment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(help_text='Subject for which this assessment is conducted', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['-date_conducted', 'subject', 'name'],
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, help_text='Marks obtained by the student', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or feedback', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(help_text='Assessment for which grade is given', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='exams.assessment')),
                ('graded_by', models.ForeignKey(blank=True, help_text='Faculty member who graded this assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assessments', to='users.facultyprofile')),
                ('student', models.ForeignKey(help_text='Student who received this grade', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'assessment')},
            },
        ),
    ]
