# Generated by Django 6.0.2 on 2026-04-18 07:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_subject_faculty'),
        ('exams', '0002_alter_assessment_id_alter_grade_id'),
        ('users', '0007_alter_studentprofile_options_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, help_text='Total marks obtained by the student', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_marks', models.DecimalField(decimal_places=2, help_text='Total maximum marks for the subject', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade_letter', models.CharField(choices=[('A+', 'A+ (Outstanding)'), ('A', 'A (Excellent)'), ('B+', 'B+ (Very Good)'), ('B', 'B (Good)'), ('C+', 'C+ (Above Average)'), ('C', 'C (Average)'), ('D', 'D (Pass)'), ('F', 'F (Fail)')], help_text='Letter grade (A+, A, B+, B, C+, C, D, F)', max_length=2)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or feedback', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(blank=True, help_text='Faculty member who assigned the grade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_students', to='users.facultyprofile')),
                ('student', models.ForeignKey(help_text='Student receiving the grade', on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='users.studentprofile')),
                ('subject', models.ForeignKey(help_text='Subject for which grade is given', on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Student Grade',
                'verbose_name_plural': 'Student Grades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'subject'], name='exams_stude_student_213bfe_idx'), models.Index(fields=['subject'], name='exams_stude_subject_5aedca_idx'), models.Index(fields=['grade_letter'], name='exams_stude_grade_l_037f30_idx')],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
