# Generated by Django 6.0.2 on 2026-04-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_studentgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='grade_letter',
            field=models.CharField(choices=[('A', 'A (10)'), ('A-', 'A- (9)'), ('B', 'B (8)'), ('B-', 'B- (7)'), ('C', 'C (6)'), ('C-', 'C- (5)'), ('D', 'D (4)'), ('F', 'Fail (0)')], help_text='Letter grade (A, A-, B, B-, C, C-, D, F)', max_length=2),
        ),
    ]
