# Generated by Django 6.0.1 on 2026-02-10 05:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the department', max_length=100, unique=True)),
                ('code', models.CharField(help_text="Short code for the department (e.g., 'CSE', 'ECE')", max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the department', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the course', max_length=100)),
                ('code', models.CharField(help_text="Unique course code (e.g., 'B.Tech CSE', 'M.Sc Physics')", max_length=15, unique=True)),
                ('credits', models.PositiveIntegerField(help_text='Total credits for the course', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('duration_years', models.PositiveIntegerField(default=4, help_text='Duration of the course in years', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField(blank=True, help_text='Detailed description of the course', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Department offering this course', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.department')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['department__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the subject', max_length=100)),
                ('code', models.CharField(help_text="Subject code (e.g., 'CS101', 'MATH201')", max_length=15)),
                ('semester', models.PositiveIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8'), (9, 'Semester 9'), (10, 'Semester 10')], help_text='Semester in which this subject is taught')),
                ('credits', models.PositiveIntegerField(default=3, help_text='Credits for this subject', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this subject is mandatory or elective')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the subject', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this subject belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.course')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['course__code', 'semester', 'code'],
                'unique_together': {('code', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text="Name/identifier of the class (e.g., 'CSE-A', 'ECE-B')", max_length=50)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], help_text='Day of the week for this class', max_length=10)),
                ('start_time', models.TimeField(help_text='Start time of the class')),
                ('end_time', models.TimeField(help_text='End time of the class')),
                ('room_number', models.CharField(blank=True, help_text='Room number where the class is held', max_length=20, null=True)),
                ('academic_year', models.CharField(help_text="Academic year (e.g., '2024-25')", max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this timetable entry is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(help_text='Subject being taught in this time slot', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable Entries',
                'ordering': ['day_of_week', 'start_time', 'class_name'],
                'unique_together': {('class_name', 'day_of_week', 'start_time', 'academic_year'), ('subject', 'class_name', 'day_of_week', 'start_time', 'academic_year')},
            },
        ),
    ]
