# Generated by Django 6.0.2 on 2026-03-23 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_course_id_alter_department_id_alter_subject_id_and_more'),
        ('users', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='classroom',
            field=models.CharField(blank=True, help_text='Classroom identifier (alias for room_number)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Faculty member teaching this class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='users.facultyprofile'),
        ),
    ]
