# Generated by Django 6.0.2 on 2026-03-25 18:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_timetable_classroom_timetable_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRegistrationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Name of the custom field (e.g., 'Aadhar Number', 'Samagra ID')", max_length=100, unique=True)),
                ('field_label', models.CharField(help_text='Display label for the field', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('email', 'Email'), ('phone', 'Phone')], default='text', help_text='Type of input field', max_length=20)),
                ('dropdown_options', models.TextField(blank=True, help_text="Comma-separated options for dropdown fields (e.g., 'Option1,Option2,Option3')", null=True)),
                ('is_required', models.BooleanField(default=False, help_text='Whether this field is mandatory during registration')),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text for the input field', max_length=200, null=True)),
                ('help_text', models.CharField(blank=True, help_text='Help text to guide users', max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this field is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Registration Field',
                'verbose_name_plural': 'Custom Registration Fields',
                'ordering': ['order', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full name of the program (e.g., 'Bachelor of Technology')", max_length=100)),
                ('code', models.CharField(help_text="Short code for the program (e.g., 'BTECH', 'MSC', 'MBA')", max_length=20, unique=True)),
                ('duration_years', models.PositiveIntegerField(help_text='Duration of the program in years', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('duration_semesters', models.PositiveIntegerField(help_text='Duration of the program in semesters', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('total_credits', models.PositiveIntegerField(blank=True, help_text='Total credits required to complete the program', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('description', models.TextField(blank=True, help_text='Detailed description of the program', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this program is currently accepting students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Department offering this program', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.department')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['department__code', 'code'],
            },
        ),
    ]
