# Generated by Django 6.0.2 on 2026-04-17 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_customregistrationfield_program'),
        ('users', '0007_alter_studentprofile_options_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Faculty member assigned to teach this subject', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subjects', to='users.facultyprofile'),
        ),
    ]
