# Generated by Django 6.0.2 on 2026-04-21 08:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_subject_faculty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetablePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title/description of the timetable (e.g., 'Fall 2024 Timetable')", max_length=200)),
                ('academic_year', models.CharField(help_text="Academic year (e.g., '2024-25')", max_length=10)),
                ('semester', models.PositiveIntegerField(blank=True, help_text='Semester number (optional)', null=True)),
                ('pdf_file', models.FileField(help_text='Upload timetable PDF file', upload_to='timetables/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this timetable is currently active/visible')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department (optional - leave blank for institution-wide timetable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_pdfs', to='academics.department')),
                ('uploaded_by', models.ForeignKey(help_text='Admin who uploaded this timetable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_timetables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timetable PDF',
                'verbose_name_plural': 'Timetable PDFs',
                'ordering': ['-created_at'],
            },
        ),
    ]
