# Generated by Django 6.0.2 on 2026-03-27 05:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_customregistrationfield_program'),
        ('students', '0003_alter_academichistory_options_and_more'),
        ('users', '0007_alter_studentprofile_options_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text="Academic year (e.g., '2025-26')", max_length=10)),
                ('semester', models.CharField(help_text="Semester period (e.g., 'Jan-Jun 2026')", max_length=50)),
                ('institute_fee_paid', models.BooleanField(default=False, help_text='Whether institute fee has been paid')),
                ('hostel_fee_paid', models.BooleanField(default=False, help_text='Whether hostel fee has been paid')),
                ('hostel_room_no', models.CharField(blank=True, help_text='Hostel room number (if applicable)', max_length=20, null=True)),
                ('total_credits', models.PositiveIntegerField(default=0, help_text='Total credits registered for this semester')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_registrations', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-academic_year', '-semester'],
                'unique_together': {('student', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='FeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utr_no', models.CharField(help_text='Unique Transaction Reference number', max_length=50)),
                ('bank_name', models.CharField(help_text='Name of the bank', max_length=100)),
                ('transaction_date', models.DateField(help_text='Date of transaction')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('account_debited', models.CharField(help_text='Account from which amount was debited', max_length=100)),
                ('account_credited', models.CharField(help_text='Account to which amount was credited', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_transactions', to='students.semesterregistration')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_backlog', models.BooleanField(default=False, help_text='Whether this is a backlog subject')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='academics.subject')),
                ('semester_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_courses', to='students.semesterregistration')),
            ],
            options={
                'ordering': ['is_backlog', 'subject__code'],
                'unique_together': {('semester_registration', 'subject')},
            },
        ),
    ]
