# Generated by Django 6.0.2 on 2026-04-21 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_semesterregistration_feetransaction_registeredcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetransaction',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='Upload fee receipt screenshot/image (JPG, PNG, or PDF)', null=True, upload_to='fee_receipts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
