# Generated by Django 6.0.2 on 2026-04-21 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_feetransaction_receipt_image'),
        ('users', '0007_alter_studentprofile_options_studentprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterregistration',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes for approval/rejection'),
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin approval status for this registration', max_length=20),
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when registration was approved/rejected', null=True),
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved/rejected this registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='semesterregistration',
            index=models.Index(fields=['approval_status'], name='students_se_approva_cbe919_idx'),
        ),
        migrations.AddIndex(
            model_name='semesterregistration',
            index=models.Index(fields=['student', 'approval_status'], name='students_se_student_f44848_idx'),
        ),
    ]
