# Generated by Django 4.2.28 on 2026-02-11 05:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_alter_course_id_alter_department_id_alter_subject_id_and_more'),
        ('users', '0004_alter_customuser_id_alter_facultyprofile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(help_text='Semester number (e.g., 1, 2, 3)', validators=[django.core.validators.MinValueValidator(1)])),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2025-2026, 2026)', max_length=10)),
                ('section', models.CharField(blank=True, help_text='Section or class group (e.g., A, B, C)', max_length=10, null=True)),
                ('max_students', models.IntegerField(blank=True, help_text='Maximum number of students allowed in this class', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(help_text='Faculty member assigned to teach the subject', on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='users.facultyprofile')),
                ('subject', models.ForeignKey(help_text='Subject being taught', on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Class Assignment',
                'verbose_name_plural': 'Class Assignments',
                'ordering': ['-academic_year', '-semester', 'subject__name'],
                'unique_together': {('faculty', 'subject', 'semester', 'academic_year', 'section')},
            },
        ),
    ]
