# Generated by Django 6.0.2 on 2026-03-15 07:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_course_id_alter_department_id_alter_subject_id_and_more'),
        ('faculty', '0001_initial'),
        ('users', '0005_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classassignment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='classassignment',
            unique_together={('subject', 'semester', 'academic_year')},
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='academic_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='users.facultyprofile'),
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='semester',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='academics.subject'),
        ),
        migrations.RemoveField(
            model_name='classassignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='classassignment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='classassignment',
            name='max_students',
        ),
        migrations.RemoveField(
            model_name='classassignment',
            name='section',
        ),
        migrations.RemoveField(
            model_name='classassignment',
            name='updated_at',
        ),
    ]
